### ISSUE TITLE
Leaving out params can lead to an error

### ISSUE THREAD

**Issue by jgosmann** [jgosmann/psyrun#18]
```python
Param(a=[1], b=[2]) + Param(a=[2], c=[3])
```

```
Traceback (most recent call last):
  File "/work/jgosmann/math-paper/empirical_error2/empirical_error2:split.py", line 10, in <module>
    Splitter('/work/jgosmann/math-paper/empirical_error2', task.pspace, 64, 64).split()
  File "/home/jgosmann/.local/lib/python2.7/site-packages/psyrun-0.1-py2.7.egg/psyrun/split.py", line 36, in split
    save_infile(block, os.path.join(self.indir, filename))
  File "/home/jgosmann/.local/lib/python2.7/site-packages/psyrun-0.1-py2.7.egg/psyrun/io.py", line 9, in save_infile
    h5.create_array('/pspace', k, v, createparents=True)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/tables/file.py", line 1159, in create_array
    obj=obj, title=title, byteorder=byteorder)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/tables/array.py", line 187, in __init__
    byteorder, _log)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/tables/leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/tables/node.py", line 269, in __init__
    self._v_objectid = self._g_create()
  File "/home/jgosmann/.local/lib/python2.7/site-packages/tables/array.py", line 204, in _g_create
    raise TypeError("Array objects cannot currently deal with void, "
TypeError: Array objects cannot currently deal with void, unicode or object arrays
```

**Comment by jgosmann** [comment]
This is probably invalid. The error was probably caused by a multidimensional array. See issue #23.
