### ISSUE TITLE
DistributeSubtaskMapper fails

### ISSUE THREAD

**Issue by jgosmann** [jgosmann/psyrun#44]
```
Traceback (most recent call last):
  File "/work/jgosmann/tcm/tcm_contdist/tcm_contdist:process:0.py", line 17, in <module>
    execute, '/work/jgosmann/tcm/tcm_contdist/in/0.npz', '/work/jgosmann/tcm/tcm_contdist/out/0.npz')
  File "/home/jgosmann/software/psyrun/psyrun/processing.py", line 144, in start
    data = self.mapper(fn, pspace, **self.mapper_kwargs)
  File "/home/jgosmann/software/psyrun/psyrun/mapper.py", line 64, in map_pspace
    return dict_concat(list(get_result(fn, p) for p in pspace.iterate()))
  File "/home/jgosmann/software/psyrun/psyrun/mapper.py", line 64, in <genexpr>
    return dict_concat(list(get_result(fn, p) for p in pspace.iterate()))
  File "/home/jgosmann/software/psyrun/psyrun/mapper.py", line 34, in get_result
    result.update(fn(**params))
ValueError: dictionary update sequence element #0 has length 71; 2 is required
--- SharcNET Job Epilogue ---
              job id: 5379000
         exit status: 1
        elapsed time: 7.4h / 30.0h (24 %)
      virtual memory: 1.0G / 3.9G (24 %)

Job returned with status 1.
WARNING: Job only used 24 % of its requested walltime.
WARNING: Job only used 24% of its requested memory.
```

**Comment by jgosmann** [comment]
Probably a problem in ctn_benchmarks
